### ISSUE TITLE
Action stopped deploying app files

### ISSUE THREAD

**Issue by yaeszlo** [ayeressian/bunnycdn-storage-deploy#33]
Seems like the action stopped deploying the build files. It was working fine for a year, and I haven't changed anything in the workflow. 
The build step works and builds all the files, it takes a minute to do, but the deployment step takes 0s 
![image](https://github.com/ayeressian/bunnycdn-storage-deploy/assets/82897497/3a09d311-1ee9-43cf-a1a2-b2151cdddd79)

I looked into the changelog and it doesn't seem any breaking changes were introduced in this action? 
Any ideas what could be going on? Maybe related to recent set-output deprecation?

**Comment by ayeressian** [comment]
@yaeszlo thank you for bringing this issue up. The problem is incorrect versioning. Unfortunately, I've introduced breaking change in minor release. Please from now on use version v2.0.0. You need to add storagePassword and upload inputs. Please have a look at the updated readme file. Let me know if you still face problems. Thanks!

**Comment by yaeszlo** [comment]
Thanks you for clarification. Using the version from current readme file I get: 
![image](https://github.com/ayeressian/bunnycdn-storage-deploy/assets/82897497/6fbe7780-3cd1-4843-a10b-2f5552c3acb3)
